### ISSUE TITLE
Add support for Cluster provisioning

### ISSUE THREAD

**Issue by russellb** [metal3-io/cluster-api-provider-baremetal#67]
This is probably more of an epic that needs to be broken down into smaller tasks, but this is a starting point.

We started cluster-api-provider-baremetal only supporting the Machine actuator interface.

Next we need to add optional support for the higher level cluster-api primitives that allow provisioning a cluster configured with kubeadm.  

It would be nice to see what code could be shared with other providers in terms of the kubeadm integration.  Each provider seems to have its own code for this, and some of this should be shared.  There's also a node lifecycle workstream under cluster-api right now looking at these issues, among other things.

**Comment by fengye87** [comment]
@russellb So I was trying out the cluster-api with my experimental provider, and just came across this same problem - cluster provisioning.

Like you said, each provider has its own code for this, but they share some common parts. Also it seems that cluster-api is moving to v1alpha2 with an effort to make bootstrap implementations reusable, but it might be a long wait. Since it has been 2 months after you fired this issue at the first place, so I was wondering if you have any new thoughts or updates to share?

**Comment by russellb** [comment]
Yeah, I figured v1alpha2 support of reusable bootstrap providers was where we would really tackle this.  Effort is probably best put into helping upstream `cluster-api` move that work along.

Another thing we could do is put some PoC kubeadm based scripts in metal3-dev-env, just for simple test/dev/demo purposes.  What we need is scripts that generate the right cloud-init configuration and put that in a secret.  That would be interesting just to play with, but wouldn't be real cluster API support.

**Comment by dhellmann** [comment]
I agree that, given the direction the cluster API group is going, we should focus on helping there. In an ideal world, we wouldn't have to write any additional code at all for metal3 to work with the new cluster API because there would be a generic cluster API provider based on using Machine objects.

**Comment by fengye87** [comment]
Yeah, that sounds reasonable. I've written a docker-machine driver in earlier days, and put it to work with Rancher. The coding experience was great. I just need to do my job, that is to create a machine with docker inside and with password-less SSH enabled. That's it, Rancher would do all the rest heavy lifting of provisioning a K8s cluster. I'm really hoping that cluster-api v1alpha2 would land somewhere like this.

Or, I'm thinking I could also make a cluster-api provider based on docker-machine. In the way that the whole provider thing would be separated with a vendor specific docker-machine driver, and a generic cluster managing tool based on kubeadm. But that would require SSH access rather than cloud-init.

**Comment by dhellmann** [comment]
I think this work is in progress in the new cluster-api-provider-metal3 repo.
