### ISSUE TITLE
Machine controller does not see if a chosen BareMetalHost is deleted

### ISSUE THREAD

**Issue by russellb** [metal3-io/cluster-api-provider-baremetal#87]
cluster-api-provider-baremetal was originally coded to assume that a BareMetalHost could not be deleted if it was associated with a Machine.  There's a bug open to prevent this case in the baremetal-operator: https://github.com/metal3-io/baremetal-operator/issues/34

The BareMetalHost spec is changing this reference from MachineRef to a more generic field, so it really shouldn't make Machine related behavior based on this field.  Instead, I think we should just ensure we reconcile Machines on BareMetalHost changes to ensure we catch a Machine that no longer has its underlying BareMetalHost.

**Comment by russellb** [comment]
@mhrivnak Can you add some info on the past investigation you did around getting cluster-api-provider-baremetal to watch BareMetalHost objects?

**Comment by mhrivnak** [comment]
Here is my PoC: https://github.com/mhrivnak/cluster-api-provider-baremetal/commit/f0caa5f7186a3be48407e13e8ead325d052ac41e

It's kind of a silly approach, but since the cluster API actuator pattern doesn't give us a formal way to access the `Controller`, the only way I could think of to do so was to make a fake `Manager` that wraps the real one so we could intercept the `Controller` as it's being added.

The newly-desired deletion behavior is probably a good reason to bring that in. I can dust it off and make a PR in the next day or so unless anyone has a better idea.

FWIW I did get a user story accepted in the cluster-api that covers this, so hopefully future iterations of the cluster-api will give us a more direct way to accomplish this.

**Comment by dhellmann** [comment]
I wonder if just making the host object an owner of the machine object would cause a cascading delete and do what we want? If not that, then I wouldn't be opposed to adding some more generic delete protection behavior, like a finalizer on the host that the machine controller removes or a flag on the host that tells the BMO to delete its consumer when it is deleted. Anyway, I think we have a few options available.

**Comment by russellb** [comment]
Good point, I'll adjust the title to be a bit more generic and not suggest a specific solution

**Comment by russellb** [comment]
I believe this is resolved via #90
